// rocket.scad — 3-stage solid-fuel rocket (BIAP coursework)
//
// The OUTER MOLD LINE only — the surface the flow sees. This is a CFD input,
// not an engineering drawing: no motor internals, no bores, no charge cavities
// and no nozzles (nozzle bells broke snappyHexMesh and were dropped in a540884).
// Every section is a solid of revolution, unioned with a small overlap, so each
// exported STL is one closed manifold shell.
//
// Dimensions come from rocket-params.scad, which main.py generates; only the
// structural choices below are made here.
//
// Staging: the interstage skirt belongs to the LOWER stage and drops with it.
// Stages 2 and 3 mate flush — see the outer-mold-line note at d_ext.
//
// Unit = METERS. OpenSCAD is unitless; set SCALE=1000 for a millimetre STL.
//
// Preview:  open in OpenSCAD, F5 = preview, F6 = render.
// Export :  see Makefile — `make stls` writes one STL per flight configuration
//           (whole rocket / stage 2 & up / stage 3 & up / head) for aero analysis.
//           e.g.  openscad -D 'PART="stage2up"' -o stage2up.stl rocket.scad

$fn = 360;

// ---- Export selection (override via -D on the CLI) ----
PART  = "head";   // "all" | "stage2up" | "stage3up" | "head"
SCALE = 1;       // 1 = metres (model units); 1000 = millimetres

eps = 0.003;     // small overlap so stacked sections fuse into one manifold solid

// ============================================================================
//  Calculated parameters — d_m, L, d_kr, d_a, l_a, GENERATED by main.py.
//  Regenerate with `uv run python main.py --write-scad-params`; a bare
//  `uv run python main.py` warns on stderr when the file has drifted.
// ============================================================================
include <rocket-params.scad>

// ---- Outer mold line -------------------------------------------------------
// Condition (3.43) requires d_(м i) >= d_(a i)(1+sqrt(2)) to seat four nozzles
// on the aft dome. Stage 3 fails it: 0.83 < 0.443 * 2.414 = 1.07. Per the
// report, stage 3 keeps its narrow motor and gains an EXTERNAL SHELL at stage
// 2's diameter, so the surface the flow sees is d_ext, not d_m. Stages 2 and 3
// therefore mate FLUSH and there is no 2/3 interstage.
d_ext = [d_m[0], d_m[1], d_m[1]];


// ============================================================================
//  Structural / CAD-drawing parameters — chosen here, not produced by main.py.
// ============================================================================

// Interstage 1-2 shroud = skirt (d_ext[0]) + cone; belongs to stage 1 and
// drops with it.
H_sk12 = 0.40; H_cone21 = 0.40;   // stage 1/2 interstage (d_ext[0] -> d_ext[1])

// Navigation + head (read from the CAD drawing; edit freely).
d_ns = 0.70; L_ns = 0.18;   // navigation module
d_pl = 0.54; L_pl = 0.65;   // head / warhead body
h_nose = 0.51;              // warhead nose cone
H_s3nav   = 0.75;           // adapter stage 3 -> nav  (d_ext[2] -> 0.70)
H_navhead = 0.50;           // adapter nav -> head     (0.70 -> 0.54)

// Colours (preview only; STL has no colour). C_S indexed by stage.
C_S  = [[0.70, 0.70, 0.72],   // stage 1
        [0.76, 0.76, 0.78],   // stage 2
        [0.82, 0.82, 0.84]];  // stage 3
C_NAV = [0.30, 0.50, 0.80];   // navigation block
C_PL  = [0.80, 0.30, 0.30];   // warhead
C_STR = [0.45, 0.45, 0.48];   // structure: skirts, cones, nose

// ---------- primitive helpers ----------
module tube(d, h)             cylinder(d = d, h = h);
module frustum(d_lo, d_hi, h) cylinder(d1 = d_lo, d2 = d_hi, h = h);
module cone_tip(d, h)         cylinder(d1 = d, d2 = 0, h = h);

// stacked segments with an eps overlap into their neighbours (manifold STL)
module seg_tube(z, h, d)          translate([0, 0, z - eps]) tube(d, h + 2 * eps);
module seg_cone(z, h, d_lo, d_hi) translate([0, 0, z]) frustum(d_lo, d_hi, h);

// ---------- cumulative z (stage-1 base at z = 0) ----------
z_body1  = 0;
z_sk12   = z_body1 + L[0];     // interstage skirt 1-2, at d_ext[0]
z_cone21 = z_sk12 + H_sk12;    // cone d_ext[0] -> d_ext[1]
z_body2  = z_cone21 + H_cone21;
z_body3  = z_body2 + L[1];     // stages 2/3 mate flush (equal diameters, no skirt)
z_s3nav  = z_body3 + L[2];
z_nav    = z_s3nav + H_s3nav;
z_navhead = z_nav + L_ns;
z_head   = z_navhead + H_navhead;
z_nose   = z_head + L_pl;
z_top    = z_nose + h_nose;

// ---------- section groups (defined in global coordinates) ----------
// Stage 1 carries the interstage shroud above it, which encloses the stage-2
// aft end and drops together with stage 1. Stages 2 and 3 share a diameter
// (d_ext) and mate flush, so there is no 2/3 shroud.

module stage1_group() {
    color(C_S[0]) seg_tube(z_body1, L[0], d_ext[0]);
    color(C_STR) {
        seg_tube(z_sk12, H_sk12, d_ext[0]);        // skirt over the stage-2 aft end
        seg_cone(z_cone21, H_cone21, d_ext[0], d_ext[1]);
    }
}

module stage2_group() {
    color(C_S[1]) seg_tube(z_body2, L[1], d_ext[1]);
}

module stage3_group() {
    color(C_S[2]) seg_tube(z_body3, L[2], d_ext[2]);
}

module nav_group() {
    color(C_STR) seg_cone(z_s3nav, H_s3nav, d_ext[2], d_ns);
    color(C_NAV) seg_tube(z_nav, L_ns, d_ns);
    color(C_STR) seg_cone(z_navhead, H_navhead, d_ns, d_pl);
}

module head_group() {
    color(C_PL)  seg_tube(z_head, L_pl, d_pl);
    color(C_STR) translate([0, 0, z_nose]) cone_tip(d_pl, h_nose);
}

// ---------- configuration assembly ----------
module assembly(part) {
    if (part == "all") stage1_group();
    if (part == "all" || part == "stage2up") stage2_group();
    if (part == "all" || part == "stage2up" || part == "stage3up") {
        stage3_group();
        nav_group();
    }
    head_group();   // present in every configuration
}

// CFD orientation (arc-case convention): lay the rocket axis on +x with the nose
// tip at x = 0 pointing upstream (-x), so the freestream travels +x and meets the
// nose first. translate(-z_top) drops the nose tip (local z_top, present in every
// configuration) onto the origin; rotate([0,-90,0]) then maps the +z build axis
// onto +x, placing the aft-most plane at +x = L_model. Units stay in metres
// (SCALE = 1), so the OpenFOAM blockMesh/snappy read it with scale 1.
scale(SCALE) rotate([0, -90, 0]) translate([0, 0, -z_top]) assembly(PART);

// ---------- verification echo (Console window) ----------
echo(str("PART=", PART, "  SCALE=", SCALE));
echo(str("Motor diameters d_m   = ", d_m, " m  (internal, not modelled)"));
echo(str("Outer diameters d_ext = ", d_ext, " m"));
echo(str("Stage lengths   L   = ", L, " m"));

echo(str("Nav: d=", d_ns, " L=", L_ns, "   Head: d=", d_pl, " L=", L_pl, " + nose ", h_nose));
echo(str("Nozzle ref (not modelled): throat d_kr=", d_kr, " exit d_a=", d_a, " bell l_a=", l_a));
echo(str("Full height = ", z_top, " m"));
