// Generated by `uv run python main.py --write-scad-params`.
// Do not edit — change main.py and rerun the generator.
// Index 0/1/2 = stage 1/2/3; all lengths in metres.

d_m  = [1.57, 1.25, 1.09];  // motor-case diameter  d_(м i)
L    = [7.70, 3.95, 2.18];  // overall stage length L_i

// Nozzles are not modelled (they broke snappyHexMesh); these are
// carried for the echo block and drawing reference only.
d_kr = [0.167, 0.139, 0.080];  // nozzle throat dia    d_("кр" i)
d_a  = [0.450, 0.478, 0.416];  // nozzle exit dia      d_(a i)
l_a  = [0.389, 0.466, 0.462];  // nozzle bell length   l_(a i)
