// Generated by `uv run python main.py --write-scad-params`.
// Do not edit — change main.py and rerun the generator.
// Index 0/1/2 = stage 1/2/3; all lengths in metres.

d_m  = [1.58, 1.16, 0.83];  // motor-case diameter  d_(м i)
L    = [7.71, 4.32, 2.82];  // overall stage length L_i

// Nozzles are not modelled (they broke snappyHexMesh); these are
// carried for the echo block and drawing reference only.
d_kr = [0.167, 0.135, 0.086];  // nozzle throat dia    d_("кр" i)
d_a  = [0.451, 0.465, 0.443];  // nozzle exit dia      d_(a i)
l_a  = [0.390, 0.453, 0.491];  // nozzle bell length   l_(a i)
